import deepFreeze from '../../utils/deepFreeze.js';

const CONDITION = deepFreeze({
  min_date: 1,
  max_date: 31,
  min_order_price: 25000,
  money_seperate_standard: 1000,
  essential_order_category: '메인',
  min_index: 1,
  max_index: 12,
  christmas_sale_start_date: 1,
  christmas_sale_end_date: 25,
  christmas_sale_basic_price: 1000,
  christmas_sale_price: 100,
  sunday: 0,
  monday: 1,
  tuesday: 2,
  wednesday: 3,
  thursday: 4,
  friday: 5,
  saturday: 6,
  dessert: '디저트',
  main: '메인',
  weekday_sale_price: 2023,
  weekend_sale_price: 2023,
  special_event_date_arr: [3, 10, 17, 24, 25, 31],
  special_discount_price: 1000,
  free_gift_event_price: 120000,
  free_gift_discount_price: 25000,
  star_event_badge_price: 5000,
  star: '스타',
  tree_event_badge_price: 10000,
  tree: '트리',
  santa_event_badge_price: 20000,
  santa: '산타',
  none: '없음',
});

export default CONDITION;
